export const FETCH_HOME_POSTS = "FETCH_HOME_POSTS";
export const FETCH_RECIPE_POST = "FETCH_RECIPE_POST";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_POSTCOUNT = "FETCH_POSTCOUNT";
export const FETCH_RECIPELIST = "FETCH_RECIPELIST";
export const FETCH_SAVED_RECIPELIST = "FETCH_SAVED_RECIPELIST";
export const ISLOGGEDIN = "ISLOGGEDIN";
export const FETCH_CAT_RECIPELIST = "FETCH_CAT_RECIPELIST";